### ISSUE TITLE
[问题反馈]: TRSS崽发说说似乎没有用

### ISSUE THREAD

**Issue by bbfhbnlvnl6** [yeyang52/yenai-plugin#127]
### 反馈内容
控制台报错：
[#发说说 测试][椰奶助手-空间(Qzonesay)] TypeError: C
annot read properties of undefined (reading 'qzone.qq.com')
    at a.getck (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/lib/common/common.js:107:29)
    at default.setQzone (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/model/api/QQApi.js:84:
21)
    at Qzone.Qzonesay (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/apps/assistant/Qzone.js:
95:37)
    at PluginsLoader.deal (file:///D:/qqbot/yuanzai/TRSS-Yunzai/lib/plugins/loader.js:264:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [stack]: "TypeError: Cannot read properties of undefined (reading 'qzone.qq.com')\n" +
    '    at a.getck (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/lib/common/common.js:107:2
9)\n' +
    '    at default.setQzone (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/model/api/QQApi.j
s:84:21)\n' +
    '    at Qzone.Qzonesay (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/apps/assistant/Qzon
e.js:95:37)\n' +
    '    at PluginsLoader.deal (file:///D:/qqbot/yuanzai/TRSS-Yunzai/lib/plugins/loader.js:264:60)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  [message]: "Cannot read properties of undefined (reading 'qzone.qq.com')"
}

### 其他说明
仅在我的服务器上测试过，不知道其他人的trss崽有没有出现过该情况。
在trss崽上好友同意和群邀请似乎也没有用。
[同意][椰奶申请处理(Handle)] TypeError: (e.bot ?? Bot).pickFrie
nd(...).setFriendReq is not a function
    at NewHandle.Handle (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/apps/handle.js:161:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///D:/qqbot/yuanzai/TRSS-Yunzai/lib/plugins/loader.js:264:41) {
  [stack]: 'TypeError: (e.bot ?? Bot).pickFriend(...).setFriendReq is not a function\n' +
    '    at NewHandle.Handle (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/apps/handle.js:16
1:12)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async PluginsLoader.deal (file:///D:/qqbot/yuanzai/TRSS-Yunzai/lib/plugins/loader.js:264:41)'
,
  [message]: '(e.bot ?? Bot).pickFriend(...).setFriendReq is not a function'
}

**Comment by bbfhbnlvnl6** [comment]
[#发说说 测试][椰奶助手-空间(Qzonesay)] TypeError: C
annot read properties of undefined (reading 'qzone.qq.com')
    at a.getck (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/lib/common/common.js:107:29)
    at default.setQzone (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/model/api/QQApi.js:84:
21)
    at Qzone.Qzonesay (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/apps/assistant/Qzone.js:
95:37)
    at PluginsLoader.deal (file:///D:/qqbot/yuanzai/TRSS-Yunzai/lib/plugins/loader.js:264:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [stack]: "TypeError: Cannot read properties of undefined (reading 'qzone.qq.com')\n" +
    '    at a.getck (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/lib/common/common.js:107:2
9)\n' +
    '    at default.setQzone (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/model/api/QQApi.j
s:84:21)\n' +
    '    at Qzone.Qzonesay (file:///D:/qqbot/yuanzai/TRSS-Yunzai/plugins/yenai-plugin/apps/assistant/Qzon
e.js:95:37)\n' +
    '    at PluginsLoader.deal (file:///D:/qqbot/yuanzai/TRSS-Yunzai/lib/plugins/loader.js:264:60)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
  [message]: "Cannot read properties of undefined (reading 'qzone.qq.com')"
}

**Comment by Denfenglai** [comment]
使用的是什么协议端？该功能实测在ICQQ协议上可用
![image](https://github.com/user-attachments/assets/8760b4de-12f0-44b5-83ef-d4cca2970fe8)
其他协议端未经测试

**Comment by bbfhbnlvnl6** [comment]
使用的是OneBotv11协议LLOneBot登录 在trss上单独引用好友同意申请报错，使用**#同意全部好友申请**可以正常同意但有“2、null”的错误qq号

**Comment by TimeRainStarSky** [comment]
> 使用的是OneBotv11协议LLOneBot登录 在trss上单独引用好友同意申请报错，使用**#同意全部好友申请**可以正常同意但有“2、null”的错误qq号

OneBotv11不支持此操作

**Comment by TimeRainStarSky** [comment]
更新检查发说说是否修复

**Comment by bbfhbnlvnl6** [comment]
好的，谢谢
