### ISSUE TITLE
入群验证无法正常踢出群成员

### ISSUE THREAD

**Issue by leiji001** [yeyang52/yenai-plugin#85]
**问题描述**
入群验证失败没有踢出成员

**Yunzai版本**
Miao-Yunzai

**如何复现**
加入群聊触发入群验证

**期望结果**
对验证不通过的成员进行踢出操作

**实际结果**

> 1|Miao-Yun | [MiaoYz][04:46:51.395][MARK] [Yenai-Plugin][进群验证]收到34\*\*\*\*\*\*8的进群事件
1|Miao-Yun | [MiaoYz][04:46:51.835][INFO] succeed to send: [Group(\*\*\*\*\*\*\*\*\*)] @02欢迎新人！
1|Miao-Yun | [MiaoYz][04:46:55.395][MARK] [Yenai-Plugin][进群验证]进行34\*\*\*\*\*\*8的验证
1|Miao-Yun | [MiaoYz][04:46:55.395][MARK] [Yenai-Plugin][进群验证]答案：12494
1|Miao-Yun | [MiaoYz][04:46:58.347][INFO] succeed to send: [Group(\*\*\*\*\*\*\*\*\*)] @02 欢迎！
1|Miao-Yun | 请在「180」秒内发送
1|Miao-Yun | 「7527 + 4967」的运算结果
1|Miao-Yun | 否则将会被移出群聊
1|Miao-Yun | [MiaoYz][04:47:04.525][INFO] recv from: [Group: 审核(\*\*\*\*\*\*\*\*\*), Member: 02(34\*\*\*\*\*\*8)] 1
1|Miao-Yun | [MiaoYz][04:47:05.089][INFO] succeed to send: [Group(\*\*\*\*\*\*\*\*\*)] @02
1|Miao-Yun | ❎ 验证失败
1|Miao-Yun | 你还有「2」次机会
1|Miao-Yun | 请发送「7527 + 4967」的运算结果
1|Miao-Yun | [MiaoYz][04:47:07.153][INFO] recv from: [Group: 审核(\*\*\*\*\*\*\*\*\*), Member: 02(34\*\*\*\*\*\*8)] 1
1|Miao-Yun | [MiaoYz][04:47:07.707][INFO] succeed to send: [Group(\*\*\*\*\*\*\*\*\*)] @02
1|Miao-Yun | ❎ 验证失败
1|Miao-Yun | 你还有「1」次机会
1|Miao-Yun | 请发送「7527 + 4967」的运算结果
1|Miao-Yun | [MiaoYz][04:47:08.302][INFO] recv from: [Group: 审核(\*\*\*\*\*\*\*\*\*), Member: 02(34\*\*\*\*\*\*8)] 1
1|Miao-Yun | [MiaoYz][04:47:08.685][INFO] succeed to send: [Group(\*\*\*\*\*\*\*\*\*)] @02
1|Miao-Yun | 验证失败，请重新申请
1|Miao-Yun | [MiaoYz][04:47:08.747][ERRO] TypeError: Cannot read properties of undefined (reading '1')
1|Miao-Yun |     at Member.kick (/home/Miao-Yunzai/node_modules/.pnpm/icqq@0.6.2/node_modules/icqq/lib/member.js:181:52)
1|Miao-Yun |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|Miao-Yun |     at async Yunzai.<anonymous> (file:///home/Miao-Yunzai/plugins/yenai-plugin/apps/groupAdmin/groupVerify.js:184:12)
1|Miao-Yun | [MiaoYz][04:47:09.904][INFO] recv from: [Group: 审核(\*\*\*\*\*\*\*\*\*), Member: 02(34\*\*\*\*\*\*8)] 1

**截图**
![20814fde51c5df66e09101db0b14f913_720](https://github.com/yeyang52/yenai-plugin/assets/94916764/4fdba948-662b-4d25-befa-f59a6aa35fa4)

**其他说明**
如果您有任何其他信息或说明，请在这里添加。

**Comment by leiji001** [comment]
补充日志

> 0|Miao-Yunzai  | [MiaoYz][16:04:42.148][INFO] succeed to send: [Group(12345678)] @:)))))欢迎新人！
0|Miao-Yunzai  | Error: WHERE parameter "user_id" has invalid "undefined" value
0|Miao-Yunzai  |     at SQLiteQueryGenerator.whereItemQuery (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1743:13)
0|Miao-Yunzai  |     at /home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1734:25
0|Miao-Yunzai  |     at Array.forEach (<anonymous>)
0|Miao-Yunzai  |     at SQLiteQueryGenerator.whereItemsQuery (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1732:35)
0|Miao-Yunzai  |     at SQLiteQueryGenerator.getWhereConditions (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2075:19)
0|Miao-Yunzai  |     at SQLiteQueryGenerator.selectQuery (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:988:28)
0|Miao-Yunzai  |     at SQLiteQueryInterface.select (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)
0|Miao-Yunzai  |     at user_id.findAll (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/model.js:1140:47)
0|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|Miao-Yunzai  |     at async user_id.findOne (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/model.js:1240:12)
0|Miao-Yunzai  | [MiaoYz][16:04:42.148][ERRO] Error: WHERE parameter "user_id" has invalid "undefined" value
0|Miao-Yunzai  |     at SQLiteQueryGenerator.whereItemQuery (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1743:13)
0|Miao-Yunzai  |     at /home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1734:25
0|Miao-Yunzai  |     at Array.forEach (<anonymous>)
0|Miao-Yunzai  |     at SQLiteQueryGenerator.whereItemsQuery (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1732:35)
0|Miao-Yunzai  |     at SQLiteQueryGenerator.getWhereConditions (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2075:19)
0|Miao-Yunzai  |     at SQLiteQueryGenerator.selectQuery (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-generator.js:988:28)
0|Miao-Yunzai  |     at SQLiteQueryInterface.select (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:59)
0|Miao-Yunzai  |     at user_id.findAll (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/model.js:1140:47)
0|Miao-Yunzai  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|Miao-Yunzai  |     at async user_id.findOne (/home/Miao-Yunzai/node_modules/.pnpm/sequelize@6.35.0_sqlite3@5.1.6/node_modules/sequelize/lib/model.js:1240:12)

**Comment by leiji001** [comment]
已尝试过重新安装依赖
