### ISSUE TITLE
使用OpenShamrock机器人框架时，椰奶状态报错

### ISSUE THREAD

**Issue by jy-encore** [yeyang52/yenai-plugin#86]
**问题描述**
由于go-cqhttp无法使用，转为OpenShamrock机器人框架，椰奶状态报错

**Yunzai版本**
Trss-Yunzai 3.1.3

**如何复现**
发送#椰奶状态后，bot无回复，后台报错

[TRSSYz][10:42:54.315][MARK] [椰奶状态][state][391479132, 安可露最可爱了(1357765993)] #椰奶状态
[TRSSYz][10:42:54.759][ERRO] [椰奶状态][state]
[TRSSYz][10:42:54.759][ERRO] TypeError: Cannot read properties of undefined (reading 'version')
    at NewState.state (file:///D:/Yunzai-Bot/TRSS-Yunzai/plugins/yenai-plugin/apps/state.js:118:89)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///D:/Yunzai-Bot/TRSS-Yunzai/lib/plugins/loader.js:282:52)

注释118行后，报错如下

[TRSSYz][11:08:29.093][ERRO] [椰奶状态][state]
[TRSSYz][11:08:29.093][ERRO] Error: Cannot find module 'icqq/package.json'
Require stack:
- D:\Yunzai-Bot\TRSS-Yunzai\plugins\yenai-plugin\apps\state.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at NewState.state (file:///D:/Yunzai-Bot/TRSS-Yunzai/plugins/yenai-plugin/apps/state.js:128:139)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginsLoader.deal (file:///D:/Yunzai-Bot/TRSS-Yunzai/lib/plugins/loader.js:282:52)

**Comment by ikechan8370** [comment]
可以使用Lain-Plugin的适配器
