### ISSUE TITLE
使用#搜图功能时，Ascii2D搜索失败，错误原因：绕过Cloudflare盾失败

### ISSUE THREAD

**Issue by HHXXYY123** [yeyang52/yenai-plugin#92]
Error: Ascii2D搜索失败，错误原因：绕过Cloudflare盾失败
at doSearch (file:///C:/msys64/home/Administrator/TRSS_AllBot/Miao-Yunzai/plugins/yenai-plugin/model/PicSearch/ascii2d.js:31:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.doSearch [as SauceNAO] (file:///C:/msys64/home/Administrator/TRSS_AllBot/Miao-Yunzai/plugins/yenai-plugin/model/PicSearch/saucenao.js:45:5)
at async NewPicSearch.SauceNAO (file:///C:/msys64/home/Administrator/TRSS_AllBot/Miao-Yunzai/plugins/yenai-plugin/apps/picSearch.js:39:5)
at async PluginsLoader.deal (file:///C:/msys64/home/Administrator/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:293:54)

**Comment by Denfenglai** [comment]
椰羊：cf盾太难绕了

**Comment by devil233-ui** [comment]
> 椰羊：cf盾太难绕了

好奇这插件怎么实现的https://github.com/erzaozi/imgS-plugin/
